# DEV BRANCH

# Python exercises related with NLP

This is a level test exercise. The purpose is to get your level in python programming oriented to NLP. 

Solve (and test) the next exercises in the block below each topic. **Use your python expertise and official python manual ONLY**: [https://docs.python.org/3/](https://docs.python.org/3/). The teachers are on the classroom to help.

# Topic 1: Working with Strings

In [31]:
INPUT = 'Hello, world!'

1. Write a program that takes a string input from the user and prints the length of the string.

In [32]:
print(len(INPUT))

13

2. Create a program that converts a given string to uppercase.

In [33]:
print(INPUT.upper())

HELLO, WORLD!

3. Write a function that checks if a string contains only alphabets.

In [34]:
print(INPUT.isalpha())

False

4. Reverse a string without using slicing (e.g., string[::-1]).

In [35]:
lista = list(INPUT)
lista.reverse()
print(lista)

palabra = ''
for char in lista:
    palabra = palabra + char

print(palabra)

['!', 'd', 'l', 'r', 'o', 'w', ' ', ',', 'o', 'l', 'l', 'e', 'H']
!dlrow ,olleH

5. Count how many times a specific character appears in a string.

In [36]:
character = 'h'
numero_ocurrencias = INPUT.count(character)
print(numero_ocurrencias)

0

6. Write a function that takes two strings and checks if they are anagrams.

In [ ]:
def is_anagram(word1: str, word2: str):
    if len(word1) != len(word2):
        return False
    else:
        if sorted(word1) == sorted(word2):
            return True
        else:
            return False

print(is_anagram('hola', 'halo'))

True

7. Implement a function that removes all vowels from a given string.

In [38]:
def remove_vogal(word: str):
    vogals = ('a', 'e', 'i', 'o', 'u')
    lista = list(word)

    i = 0
    while i < len(lista):
        if lista[i] in vogals:
            lista.pop(i)  
        else:
            i = i + 1
    return lista

print(remove_vogal(INPUT))

['H', 'l', 'l', ',', ' ', 'w', 'r', 'l', 'd', '!']

8. Write a function that checks if a string is a palindrome (case-insensitive).

In [39]:
def is_palindrome(word: str):
    word.lower()
    if word == word[::-1]:
        return True
    else:
        return False

print(is_palindrome('AnA'))

True

10. Create a function that capitalizes the first letter of each word in a string.
11. Write a program to compress a string (e.g., "aaabb" -> "a3b2").
12. Implement a function to find the longest substring without repeating characters.
13. Write a program to check if a string can be rearranged into a palindrome.
14. Implement a function that removes all duplicates from a string while preserving the order of characters.
15. Write a function to find the longest common prefix among a list of strings.
16. Implement a custom split function without using Python's built-in methods.
17. Write a function to decode a given run-length encoded string (e.g., "a3b2" -> "aaabb").
18. Implement a function to check if one string is a rotation of another.
19. Create a function to find all permutations of a given string.
20. Write a function to implement a basic version of the str.index method.

# Topic 2: Working with Dictionaries and Other Data Structures

1. Create a dictionary to store the squares of numbers from 1 to 10.

In [40]:
dict_squares = {}
for x in range(1, 11):
    dict_squares[x] = x ** 2

print(dict_squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

2. Write a program to merge two dictionaries.

In [41]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

merged_dict = dict1.copy()
for key, value in dict2.items():
    merged_dict[key] = value

print(merged_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

3. Implement a function to count the occurrences of each word in a given sentence.

In [42]:
def word_count(sentence):
    words = sentence.split()
    word_counts = {}
    for word in words:
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1
    return word_counts

sentence = "test test caracola caracola hola"
print(word_count(sentence))

{'test': 2, 'caracola': 2, 'hola': 1}

4. Create a dictionary from two lists: one for keys and one for values.

In [43]:
keys = ['name', 'age', 'city']
values = ['Alice', 25, 'New York']

combined_dict = {}
for i in range(len(keys)):
    combined_dict[keys[i]] = values[i]

print(combined_dict)

{'name': 'Alice', 'age': 25, 'city': 'New York'}

5. Write a program to check if a given key exists in a dictionary.

6. Implement a function to invert a dictionary (swap keys and values).
7. Write a program to find the key with the highest value in a dictionary.

In [44]:
dict_values = {
    'a': 10, 
    'b': 30, 
    'c': 20
}

max_value = float('-inf')
max_key = None

for key, value in dict_values.items():
    if value > max_value:
        max_value = value
        max_key = key

print(f" Highest key value is '{max_key}' = {max_value}.")

 Highest key value is 'b' = 30.

8. Implement a function to sort a dictionary by its values.

9. Write a program to remove all duplicate values from a list.

In [45]:
list_duplicates = [1, 2, 2, 3, 4, 4, 5]
clean_list = []

for item in list_duplicates:
    if item not in clean_list:
        clean_list.append(item)

print(clean_list)

[1, 2, 3, 4, 5]

10. Create a set containing unique elements from a list.

11. Implement a function to find the intersection of two sets.

In [46]:
def intersection(set1, set2):
    common_elements = set()
    for item in set1:
        if item in set2:
            common_elements.add(item)
    return common_elements

print(intersection(
    {1, 2, 3, 4},
    {3, 4, 5, 6}
))

{3, 4}

12. Write a program to check if one set is a subset of another.

In [47]:
set_a = {1, 2, 3}
set_b = {1, 2, 3, 4, 5}

is_subset = True
for item in set_a:
    if item not in set_b:
        is_subset = False
        break

print(is_subset)

True

13. Implement a function to find the union of two dictionaries.

In [48]:
dict1 = {
    1,8,5
}
dict2 = {
    1, 2, 5, 7
}

print(dict1.union(dict2))

{1, 2, 5, 7, 8}

17. Write a program to check if a given list is a palindrome.

In [49]:
example = list(INPUT)

def list_to_word(list_example:list):
    palabra = ''
    for char in list_example:
        palabra +=  char
    return palabra

print(is_palindrome(list_to_word(example)))

False

14. Write a program to flatten a nested list.
15. Create a function to find the most frequent element in a list.
16. Implement a stack using a list with push and pop operations.
18. Implement a queue using a list with enqueue and dequeue operations.
19. Write a program to convert a list of tuples into a dictionary.
20. Create a function to find the common elements in two lists.

In [50]:
# ...

# Topic 3: Text Processing Including Working with Text Files

1. Write a program to read a text file and print its contents.

In [51]:
with open('files/loren_ipsum.txt', 'r') as file:
    content = file.read()
    print(content)

Holaa ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur odio eget purus congue, nec interdum neque volutpat. Phasellus posuere tristique velit, ac consectetur augue venenatis nec. Nullam congue mi suscipit magna mollis efficitur. Nulla facilisi. Quisque lorem leo, hendrerit eget malesuada nec, sodales lobortis nisl. Vestibulum ullamcorper aliquet ligula, pulvinar tincidunt tellus interdum vitae. Nam porttitor tempus magna, quis accumsan purus volutpat ac. Nam feugiat eleifend viverra. Sed et erat nunc. Nunc feugiat enim eget bibendum dictum. Curabitur sollicitudin pharetra nulla efficitur molestie. Ut blandit posuere ex, non convallis diam pretium et. Nunc sit amet auctor quam. Nulla facilisi. Fusce nec lorem auctor, faucibus ligula id, venenatis odio.

Nunc venenatis efficitur dolor, non rutrum libero suscipit sed. Fusce purus ante, suscipit vitae mollis sed, cursus a eros. Aliquam sed luctus nisl, nec suscipit mi. Quisque rutrum diam ut dolor tempus tristique. Praesent aliquam tristique lectus nec pretium. Ut imperdiet lacus lorem, eu volutpat augue tempor faucibus. Proin vulputate, orci quis faucibus congue, tellus velit lobortis augue, et ornare massa felis a nisi. Nullam est nibh, varius at mi molestie, feugiat convallis neque. Ut aliquet purus ac leo molestie sodales. In ut malesuada sapien, eu varius ligula. Praesent gravida dolor id elit ornare, quis rutrum lectus suscipit. Aenean purus diam, ultricies tempus placerat eget, pellentesque a turpis. Donec non efficitur tellus. Nulla consequat suscipit ultrices. Aliquam erat volutpat. Maecenas pharetra nibh at eleifend laoreet.

Praesent rhoncus augue et nisl tincidunt malesuada. Quisque consectetur arcu in lorem pretium commodo. Quisque blandit metus eget pretium posuere. Duis euismod sapien non diam tempor ornare. Etiam non lacus sit amet diam aliquet dignissim ac vel neque. Vivamus et arcu et dui aliquet sodales ut aliquam velit. Nullam massa urna, efficitur quis neque vel, mattis ullamcorper dui. Proin eu turpis velit. Fusce pellentesque ligula vitae odio finibus consectetur. Maecenas augue purus, porta sit amet blandit sit amet, tincidunt quis felis. In justo tortor, pellentesque ultricies sodales luctus, consequat a turpis.

Etiam molestie congue dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eu tellus eget metus fermentum interdum. Donec sed neque sapien. Nunc vestibulum dapibus tortor ac laoreet. Suspendisse malesuada erat sit amet eros pellentesque aliquam. Donec maximus ac sem ac rhoncus. Vestibulum at ante ac orci dapibus pharetra eu id magna.

Vivamus sed auctor tellus. Pellentesque libero mauris, vehicula sed felis in, euismod auctor mi. Duis varius eros eu ligula molestie, et vulputate lorem scelerisque. Ut volutpat placerat libero, non pulvinar mi viverra sed. Etiam ultrices nisi id ipsum lobortis, sit amet vulputate sem efficitur. Nullam vel tortor hendrerit, semper mauris eu, pellentesque tortor. Pellentesque at blandit mi, in ultricies est. Suspendisse potenti. Fusce tempor odio nunc, at aliquet tortor condimentum aliquet. Fusce eget ornare mauris. Mauris mattis facilisis nulla ac vestibulum. Praesent pretium quis libero a suscipit. Pellentesque hendrerit orci quis sodales viverra. Aliquam at lorem ac libero porta egestas eget quis augue.

Cras fermentum arcu ut velit finibus molestie. Donec posuere sollicitudin enim, non rutrum nisl hendrerit sit amet. Sed in arcu tincidunt, vehicula nibh non, suscipit mi. Nulla aliquet elementum molestie. Maecenas faucibus leo eget gravida luctus. Vivamus et posuere justo. Integer feugiat euismod justo non dignissim. Aliquam ipsum enim, aliquam et ornare sed, maximus ac nisl. Fusce suscipit leo ligula, eget rhoncus turpis placerat vel. Maecenas tellus quam, aliquet sed tempus nec, dignissim id magna. Nulla facilisi. Vestibulum venenatis nibh posuere bibendum pellentesque. Donec in ultrices mi, eu placerat dui. Quisque euismod diam non lacus bibendum consectetur. Vestibulum convallis vel nulla nec pharetra. Mauris sodales libero quis pharetra convallis.

Aliquam mattis arcu non nisl ornare maximus nec quis sapien. Phasellus non tortor ac arcu varius accumsan. Aenean ullamcorper sem at sodales volutpat. Phasellus nunc mauris, laoreet at sem tempus, mattis egestas elit. Duis tellus mi, vestibulum nec velit quis, ornare suscipit mauris. Praesent magna erat, commodo at imperdiet sed, gravida eu sem. Vestibulum quis orci ligula. Morbi vel arcu semper, porta elit sed, consectetur massa. Nunc et turpis in justo mollis finibus. Suspendisse vehicula a dui in rhoncus. Curabitur a accumsan quam. Cras ac interdum velit. Vivamus elementum nec erat id dignissim. Integer nec sapien ac arcu rutrum maximus. Ut ornare lobortis iaculis.

Praesent in lectus vel ex scelerisque placerat a euismod elit. Proin tempor nisi non dictum fermentum. Fusce nec magna eget odio sodales pulvinar. Proin vel iaculis arcu. In hac habitasse platea dictumst. Sed porttitor quam urna, a ullamcorper tortor consequat ut. Sed accumsan ante vel elit venenatis pretium. Etiam pulvinar vel nibh quis pellentesque. Nunc id interdum felis, ut efficitur lorem.

Phasellus vitae nisi nec purus ornare rhoncus. Proin rutrum dictum lobortis. Integer dictum vel odio nec rutrum. Nam nisi eros, facilisis in rhoncus mollis, aliquet in nisl. Proin non mollis risus. Vivamus non pellentesque enim, quis sollicitudin elit. Sed aliquam erat a bibendum fringilla. Etiam et finibus est. Quisque lorem ligula, malesuada non mattis in, porta quis libero. Morbi mollis ex ac posuere scelerisque. Quisque est elit, porttitor varius congue eget, dignissim consectetur diam.

Pellentesque sit amet fermentum sapien. Donec ante tortor, ornare nec pharetra a, feugiat sed mi. Integer in velit ut ligula dictum maximus. Duis sagittis vitae libero eu lacinia. Integer id neque nec mi sodales elementum non non nisl. Duis nec magna vel mi sollicitudin interdum. In bibendum sagittis erat sit amet tincidunt. Cras auctor rhoncus congue. Sed sapien lacus, tempor vitae turpis non, euismod maximus est. Sed sodales rhoncus euismod

¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.

2. Write a program to count the number of lines in a text file.

In [52]:
with open('files/loren_ipsum.txt', 'r') as file:
    lines = file.readlines()
    print(len(lines))

27

3. Write a program to count the number of words in a text file.

In [53]:
with open('files/loren_ipsum.txt', 'r') as file:
    words = file.read().split()
    print(len(words))

943

4. Write a program to count the number of characters in a text file.

In [54]:
with open('files/loren_ipsum.txt', 'r') as file:
    characters = file.read()
    print(len(characters))

6371

5. Write a program to find and print the longest word in a text file.

In [55]:
with open('files/loren_ipsum.txt', 'r') as file:
    words = file.read().split()
    longest_word = max(words, key=len)
    print(longest_word)

pellentesque.

6. Write a program to replace a word in a text file with another word.

In [56]:
with open('files/loren_ipsum.txt', 'r') as file:
    content = file.read().replace('Lorem', 'Holaa')
with open('files/loren_ipsum.txt', 'w') as file:
    file.write(content)
with open('files/loren_ipsum.txt', 'r') as file:
    content = file.read()
    print(content)

Holaa ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur odio eget purus congue, nec interdum neque volutpat. Phasellus posuere tristique velit, ac consectetur augue venenatis nec. Nullam congue mi suscipit magna mollis efficitur. Nulla facilisi. Quisque lorem leo, hendrerit eget malesuada nec, sodales lobortis nisl. Vestibulum ullamcorper aliquet ligula, pulvinar tincidunt tellus interdum vitae. Nam porttitor tempus magna, quis accumsan purus volutpat ac. Nam feugiat eleifend viverra. Sed et erat nunc. Nunc feugiat enim eget bibendum dictum. Curabitur sollicitudin pharetra nulla efficitur molestie. Ut blandit posuere ex, non convallis diam pretium et. Nunc sit amet auctor quam. Nulla facilisi. Fusce nec lorem auctor, faucibus ligula id, venenatis odio.

Nunc venenatis efficitur dolor, non rutrum libero suscipit sed. Fusce purus ante, suscipit vitae mollis sed, cursus a eros. Aliquam sed luctus nisl, nec suscipit mi. Quisque rutrum diam ut dolor tempus tristique. Praesent aliquam tristique lectus nec pretium. Ut imperdiet lacus lorem, eu volutpat augue tempor faucibus. Proin vulputate, orci quis faucibus congue, tellus velit lobortis augue, et ornare massa felis a nisi. Nullam est nibh, varius at mi molestie, feugiat convallis neque. Ut aliquet purus ac leo molestie sodales. In ut malesuada sapien, eu varius ligula. Praesent gravida dolor id elit ornare, quis rutrum lectus suscipit. Aenean purus diam, ultricies tempus placerat eget, pellentesque a turpis. Donec non efficitur tellus. Nulla consequat suscipit ultrices. Aliquam erat volutpat. Maecenas pharetra nibh at eleifend laoreet.

Praesent rhoncus augue et nisl tincidunt malesuada. Quisque consectetur arcu in lorem pretium commodo. Quisque blandit metus eget pretium posuere. Duis euismod sapien non diam tempor ornare. Etiam non lacus sit amet diam aliquet dignissim ac vel neque. Vivamus et arcu et dui aliquet sodales ut aliquam velit. Nullam massa urna, efficitur quis neque vel, mattis ullamcorper dui. Proin eu turpis velit. Fusce pellentesque ligula vitae odio finibus consectetur. Maecenas augue purus, porta sit amet blandit sit amet, tincidunt quis felis. In justo tortor, pellentesque ultricies sodales luctus, consequat a turpis.

Etiam molestie congue dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eu tellus eget metus fermentum interdum. Donec sed neque sapien. Nunc vestibulum dapibus tortor ac laoreet. Suspendisse malesuada erat sit amet eros pellentesque aliquam. Donec maximus ac sem ac rhoncus. Vestibulum at ante ac orci dapibus pharetra eu id magna.

Vivamus sed auctor tellus. Pellentesque libero mauris, vehicula sed felis in, euismod auctor mi. Duis varius eros eu ligula molestie, et vulputate lorem scelerisque. Ut volutpat placerat libero, non pulvinar mi viverra sed. Etiam ultrices nisi id ipsum lobortis, sit amet vulputate sem efficitur. Nullam vel tortor hendrerit, semper mauris eu, pellentesque tortor. Pellentesque at blandit mi, in ultricies est. Suspendisse potenti. Fusce tempor odio nunc, at aliquet tortor condimentum aliquet. Fusce eget ornare mauris. Mauris mattis facilisis nulla ac vestibulum. Praesent pretium quis libero a suscipit. Pellentesque hendrerit orci quis sodales viverra. Aliquam at lorem ac libero porta egestas eget quis augue.

Cras fermentum arcu ut velit finibus molestie. Donec posuere sollicitudin enim, non rutrum nisl hendrerit sit amet. Sed in arcu tincidunt, vehicula nibh non, suscipit mi. Nulla aliquet elementum molestie. Maecenas faucibus leo eget gravida luctus. Vivamus et posuere justo. Integer feugiat euismod justo non dignissim. Aliquam ipsum enim, aliquam et ornare sed, maximus ac nisl. Fusce suscipit leo ligula, eget rhoncus turpis placerat vel. Maecenas tellus quam, aliquet sed tempus nec, dignissim id magna. Nulla facilisi. Vestibulum venenatis nibh posuere bibendum pellentesque. Donec in ultrices mi, eu placerat dui. Quisque euismod diam non lacus bibendum consectetur. Vestibulum convallis vel nulla nec pharetra. Mauris sodales libero quis pharetra convallis.

Aliquam mattis arcu non nisl ornare maximus nec quis sapien. Phasellus non tortor ac arcu varius accumsan. Aenean ullamcorper sem at sodales volutpat. Phasellus nunc mauris, laoreet at sem tempus, mattis egestas elit. Duis tellus mi, vestibulum nec velit quis, ornare suscipit mauris. Praesent magna erat, commodo at imperdiet sed, gravida eu sem. Vestibulum quis orci ligula. Morbi vel arcu semper, porta elit sed, consectetur massa. Nunc et turpis in justo mollis finibus. Suspendisse vehicula a dui in rhoncus. Curabitur a accumsan quam. Cras ac interdum velit. Vivamus elementum nec erat id dignissim. Integer nec sapien ac arcu rutrum maximus. Ut ornare lobortis iaculis.

Praesent in lectus vel ex scelerisque placerat a euismod elit. Proin tempor nisi non dictum fermentum. Fusce nec magna eget odio sodales pulvinar. Proin vel iaculis arcu. In hac habitasse platea dictumst. Sed porttitor quam urna, a ullamcorper tortor consequat ut. Sed accumsan ante vel elit venenatis pretium. Etiam pulvinar vel nibh quis pellentesque. Nunc id interdum felis, ut efficitur lorem.

Phasellus vitae nisi nec purus ornare rhoncus. Proin rutrum dictum lobortis. Integer dictum vel odio nec rutrum. Nam nisi eros, facilisis in rhoncus mollis, aliquet in nisl. Proin non mollis risus. Vivamus non pellentesque enim, quis sollicitudin elit. Sed aliquam erat a bibendum fringilla. Etiam et finibus est. Quisque lorem ligula, malesuada non mattis in, porta quis libero. Morbi mollis ex ac posuere scelerisque. Quisque est elit, porttitor varius congue eget, dignissim consectetur diam.

Pellentesque sit amet fermentum sapien. Donec ante tortor, ornare nec pharetra a, feugiat sed mi. Integer in velit ut ligula dictum maximus. Duis sagittis vitae libero eu lacinia. Integer id neque nec mi sodales elementum non non nisl. Duis nec magna vel mi sollicitudin interdum. In bibendum sagittis erat sit amet tincidunt. Cras auctor rhoncus congue. Sed sapien lacus, tempor vitae turpis non, euismod maximus est. Sed sodales rhoncus euismod

¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.
¿Quieres saber cuanto vale tu coche?.

7. Write a program to append a line to a text file.

In [57]:
with open('files/loren_ipsum.txt', 'a') as file:
    file.write('\n¿Quieres saber cuanto vale tu coche?.')

8. Write a program to reverse the contents of a text file and write it to a new file.

In [58]:
with open('files/loren_ipsum.txt', 'r') as file:
    content = file.read()[::-1]
with open('files/reversed_file.txt', 'w') as file:
    file.write(content)

9. Write a program to find the frequency of each word in a text file.

10. Write a program to read a text file and print only the lines that start with a specific letter.

In [59]:
letter = 'A'
with open('files/loren_ipsum.txt', 'r') as file:
    for line in file:
        if line.startswith(letter):
            print(line.strip())

Aliquam mattis arcu non nisl ornare maximus nec quis sapien. Phasellus non tortor ac arcu varius accumsan. Aenean ullamcorper sem at sodales volutpat. Phasellus nunc mauris, laoreet at sem tempus, mattis egestas elit. Duis tellus mi, vestibulum nec velit quis, ornare suscipit mauris. Praesent magna erat, commodo at imperdiet sed, gravida eu sem. Vestibulum quis orci ligula. Morbi vel arcu semper, porta elit sed, consectetur massa. Nunc et turpis in justo mollis finibus. Suspendisse vehicula a dui in rhoncus. Curabitur a accumsan quam. Cras ac interdum velit. Vivamus elementum nec erat id dignissim. Integer nec sapien ac arcu rutrum maximus. Ut ornare lobortis iaculis.

11. Write a program to create a new file that contains only unique words from a given text file.

In [60]:
with open('files/loren_ipsum.txt', 'r') as file:
    unique_words = set(file.read().split())
with open('files/unique_words.txt', 'w') as file:
    file.write('\n'.join(unique_words))

12. Write a program to merge the contents of two text files into a third file.

In [61]:
with open('files/loren_ipsum.txt', 'r') as file1, open('files/reversed_file.txt', 'r') as file2:
    merged_content = file1.read() + '\n' + file2.read()
with open('files/merged_file.txt', 'w') as file:
    file.write(merged_content)

13. Write a program to remove all punctuation from a text file and write the result to a new file.

In [62]:
word_to_count = 'ipsum'
with open('files/loren_ipsum.txt', 'r') as file:
    count = file.read().split().count(word_to_count)
    print(count)

4

14. Write a program to count the occurrences of a specific word in a text file.

In [63]:
word_to_find = 'specific'
with open('files/loren_ipsum.txt', 'r') as file:
    exists = word_to_find in file.read()
    print(exists)

False

15. Write a program to check if a specific word exists in a text file.

In [64]:
with open('files/loren_ipsum.txt', 'r') as file:
    content = file.read().title()
with open('files/capitalized_file.txt', 'w') as file:
    file.write(content)

16. Write a program to split a text file into multiple smaller files, each containing a fixed number of lines.
17. Write a program to find all palindromic words in a text file.
18. Write a program to sort the words in a text file alphabetically and save the result to a new file.
19. Write a program to capitalize the first letter of every word in a text file.
20. Write a program to remove duplicate lines from a text file and save the result to a new file.

In [65]:
# ...

# Topic 4: Pandas Usage Oriented Processing

In [66]:
import pandas as pd

1. Create a DataFrame from a dictionary of lists and display it.

In [67]:
data = {
    'Name': ['Luis', 'Sara', 'Mery', None],
    'Age': [33, 14, 3, 99],
    'City': ['A Coruña', 'Lugo', 'Santiago', '']
}
df = pd.DataFrame(data)
display(df)

   Name  Age      City
0  Luis   33  A Coruña
1  Sara   14      Lugo
2  Mery    3  Santiago
3  None   99

2. Add a new column to an existing DataFrame based on calculations from other columns.

In [68]:
df['Age + 5 years'] = df['Age'] + 5
display(df)

   Name  Age      City  Age + 5 years
0  Luis   33  A Coruña             38
1  Sara   14      Lugo             19
2  Mery    3  Santiago              8
3  None   99                      104

3. Filter rows in a DataFrame based on a condition.

In [69]:
filtered_df = df[df['City'] == 'Lugo']
print(filtered_df)

   Name  Age  City  Age + 5 years
1  Sara   14  Lugo             19

4. Sort a DataFrame by a specific column in ascending order.

In [70]:
sorted_df = df.sort_values(by='Age')
print(sorted_df)

   Name  Age      City  Age + 5 years
2  Mery    3  Santiago              8
1  Sara   14      Lugo             19
0  Luis   33  A Coruña             38
3  None   99                      104

5. Write a program to rename the columns of a DataFrame.

In [71]:
df_renamed = df.rename(columns={
    'Name': 'Full Name', 
    'Age': 'Years old', 
    'City': 'Place of brith', 
    'Age + 5 years': '5 years older'
})
print(df_renamed)

  Full Name  Years old Place of brith  5 years older
0      Luis         33       A Coruña             38
1      Sara         14           Lugo             19
2      Mery          3       Santiago              8
3      None         99                           104

6. Drop rows with missing values from a DataFrame.

In [72]:
df_dropped = df.dropna()
print(df_dropped)

   Name  Age      City  Age + 5 years
0  Luis   33  A Coruña             38
1  Sara   14      Lugo             19
2  Mery    3  Santiago              8

7. Write a program to fill missing values in a DataFrame with a default value.

In [73]:
df_filled = df.fillna(0)
display(df_filled)

   Name  Age      City  Age + 5 years
0  Luis   33  A Coruña             38
1  Sara   14      Lugo             19
2  Mery    3  Santiago              8
3     0   99                      104

8. Group a DataFrame by a specific column and calculate the mean of each group.

In [74]:
grouped_mean = df.groupby('City')['Age'].mean()
print(grouped_mean)

City
            99.0
A Coruña    33.0
Lugo        14.0
Santiago     3.0
Name: Age, dtype: float64

9. Write a program to merge two DataFrames on a common column.

In [ ]:
df1 = pd.DataFrame(
    {
        'id_number': [1, 2, 3], 
        'Name': ['Alice', 'Bob', 'Charlie']
    }
)
df2 = pd.DataFrame(
    {
        'id_number': [1, 2, 4], 
        'poitns': [85, 90, 95]
    }
)

# It is based on the same idea used in SQL.
for type in ['inner', 'left', 'right', 'outer']:
    merged_df = pd.merge(
        df1, df2, 
        on = 'id_number', 
        how = type
    )
    display(merged_df)

   id_number   Name  poitns
0          1  Alice      85
1          2    Bob      90

   id_number     Name  poitns
0          1    Alice    85.0
1          2      Bob    90.0
2          3  Charlie     NaN

   id_number   Name  poitns
0          1  Alice      85
1          2    Bob      90
2          4    NaN      95

   id_number     Name  poitns
0          1    Alice    85.0
1          2      Bob    90.0
2          3  Charlie     NaN
3          4      NaN    95.0

10. Write a program to concatenate two DataFrames vertically.

In [76]:
df3 = pd.DataFrame({'Name': ['David'], 'Age': [40], 'City': ['Miami']})

concatenated_df = pd.concat([df, df3], ignore_index=True)
display(concatenated_df)

    Name  Age      City  Age + 5 years
0   Luis   33  A Coruña           38.0
1   Sara   14      Lugo           19.0
2   Mery    3  Santiago            8.0
3   None   99                    104.0
4  David   40     Miami            NaN

11. Create a new column in a DataFrame that is the result of applying a custom function to an existing column.

In [77]:
def age_category(age):
    if age < 30:
        return 'Young'
    else: return 'Eldery'

df['Age Category'] = df['Age'].apply(age_category)

display(df)

   Name  Age      City  Age + 5 years Age Category
0  Luis   33  A Coruña             38       Eldery
1  Sara   14      Lugo             19        Young
2  Mery    3  Santiago              8        Young
3  None   99                      104       Eldery

12. Write a program to count the unique values in a specific column of a DataFrame.

In [78]:
unique = df['City'].nunique()
print(unique)

4

13. Write a program to find the maximum value in a specific column of a DataFrame.

In [79]:
max_age = df['Age'].max()
print(max_age)

99

14. Write a program to filter a DataFrame based on multiple conditions.

In [80]:
multi_filtered_df = df[(df['Age + 5 years'] > 15) & (df['City'] == 'Lugo')]
display(multi_filtered_df)

   Name  Age  City  Age + 5 years Age Category
1  Sara   14  Lugo             19        Young

15. Write a program to calculate the correlation matrix of a DataFrame.

In [81]:
correlation_matrix = df.corr(numeric_only=True)
display(correlation_matrix)

               Age  Age + 5 years
Age            1.0            1.0
Age + 5 years  1.0            1.0

16. Write a program to apply a lambda function to every element of a column in a DataFrame.

In [82]:
df['Double Age'] = df['Age'].apply(lambda x: x * 2)
display(df)

   Name  Age      City  Age + 5 years Age Category  Double Age
0  Luis   33  A Coruña             38       Eldery          66
1  Sara   14      Lugo             19        Young          28
2  Mery    3  Santiago              8        Young           6
3  None   99                      104       Eldery         198

17. Write a program to drop duplicate rows from a DataFrame.

In [83]:
df_duplicates = pd.DataFrame(
    {
        'A': [1, 2, 2, 3],
        'B': [4, 5, 5, 6]
    }
)
df_no_duplicates = df_duplicates.drop_duplicates()
display(df_no_duplicates)

   A  B
0  1  4
1  2  5
3  3  6

18. Write a program to reset the index of a DataFrame.

In [84]:
reset_index_df = df.reset_index(drop=True)
display(reset_index_df)

   Name  Age      City  Age + 5 years Age Category  Double Age
0  Luis   33  A Coruña             38       Eldery          66
1  Sara   14      Lugo             19        Young          28
2  Mery    3  Santiago              8        Young           6
3  None   99                      104       Eldery         198

19. Write a program to save a DataFrame to a CSV file.

In [86]:
df.to_csv('files/output.csv', index=False)

20. Write a program to read a CSV file into a DataFrame and display the first five rows.

In [ ]:
read_df = pd.read_csv('files/output.csv')
display(read_df.head())

   Name  Age      City  Age + 5 years Age Category  Double Age
0  Luis   33  A Coruña             38       Eldery          66
1  Sara   14      Lugo             19        Young          28
2  Mery    3  Santiago              8        Young           6
3   NaN   99       NaN            104       Eldery         198